Basic Foundation for a Keeper Security JSON Importer
buttercup/buttercup-importer pull request #73
Opened 2024-04-18 06:33 UTC by muddykat-tech

Currently I've an issue with creating entries as there seems to be some instancing issue wuen I build a local version of importer.

2024-04-27 19:03 UTC, perry-mitchell requested changes

2024-04-27 19:03 UTC, perry-mitchell commented on .project
I'm not familiar with this filetype, and why it'd be needed over `package.json`?

2024-04-27 19:03 UTC, perry-mitchell commented on source/index.js
Any chance you might consider adding a test vault, and test specs for this new importer? Otherwise it's hard to verify its stability.

2024-04-28 04:10 UTC, muddykat-tech commented on .project
I think that's an artifact from my IDE.

2024-04-28 04:12 UTC, muddykat-tech commented on source/index.js
Makes sense, I'll work on setting up a test vault and test specs for the new importer.

2024-04-28 09:55 UTC, perry-mitchell approved these changes

2024-04-28 09:56 UTC, perry-mitchell commented
Thank you @muddykat-tech! I'll do my best to get this released today.

Long term plans include moving this entire repo into the core, along with the exporter, in case you see this project archived soon.

2024-04-28 09:56 UTC, merged